/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoumettreRouteImport } from './routes/soumettre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnoncesIndexRouteImport } from './routes/annonces.index'
import { Route as AnnoncesIdRouteImport } from './routes/annonces.$id'
import { Route as ApiPublicAdminRouteImport } from './routes/api/public/admin'
import { Route as ApiPublicModerationRejectRouteImport } from './routes/api/public/moderation/reject'
import { Route as ApiPublicModerationApproveRouteImport } from './routes/api/public/moderation/approve'

const SoumettreRoute = SoumettreRouteImport.update({
  id: '/soumettre',
  path: '/soumettre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIndexRoute = AnnoncesIndexRouteImport.update({
  id: '/annonces/',
  path: '/annonces/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesIdRoute = AnnoncesIdRouteImport.update({
  id: '/annonces/$id',
  path: '/annonces/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminRoute = ApiPublicAdminRouteImport.update({
  id: '/api/public/admin',
  path: '/api/public/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicModerationRejectRoute =
  ApiPublicModerationRejectRouteImport.update({
    id: '/api/public/moderation/reject',
    path: '/api/public/moderation/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicModerationApproveRoute =
  ApiPublicModerationApproveRouteImport.update({
    id: '/api/public/moderation/approve',
    path: '/api/public/moderation/approve',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/soumettre': typeof SoumettreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/moderation/approve': typeof ApiPublicModerationApproveRoute
  '/api/public/moderation/reject': typeof ApiPublicModerationRejectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/soumettre': typeof SoumettreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/annonces': typeof AnnoncesIndexRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/moderation/approve': typeof ApiPublicModerationApproveRoute
  '/api/public/moderation/reject': typeof ApiPublicModerationRejectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/soumettre': typeof SoumettreRoute
  '/annonces/$id': typeof AnnoncesIdRoute
  '/annonces/': typeof AnnoncesIndexRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/moderation/approve': typeof ApiPublicModerationApproveRoute
  '/api/public/moderation/reject': typeof ApiPublicModerationRejectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/soumettre'
    | '/annonces/$id'
    | '/annonces/'
    | '/api/public/admin'
    | '/api/public/moderation/approve'
    | '/api/public/moderation/reject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/soumettre'
    | '/annonces/$id'
    | '/annonces'
    | '/api/public/admin'
    | '/api/public/moderation/approve'
    | '/api/public/moderation/reject'
  id:
    | '__root__'
    | '/'
    | '/soumettre'
    | '/annonces/$id'
    | '/annonces/'
    | '/api/public/admin'
    | '/api/public/moderation/approve'
    | '/api/public/moderation/reject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoumettreRoute: typeof SoumettreRoute
  AnnoncesIdRoute: typeof AnnoncesIdRoute
  AnnoncesIndexRoute: typeof AnnoncesIndexRoute
  ApiPublicAdminRoute: typeof ApiPublicAdminRoute
  ApiPublicModerationApproveRoute: typeof ApiPublicModerationApproveRoute
  ApiPublicModerationRejectRoute: typeof ApiPublicModerationRejectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soumettre': {
      id: '/soumettre'
      path: '/soumettre'
      fullPath: '/soumettre'
      preLoaderRoute: typeof SoumettreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/': {
      id: '/annonces/'
      path: '/annonces'
      fullPath: '/annonces/'
      preLoaderRoute: typeof AnnoncesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces/$id': {
      id: '/annonces/$id'
      path: '/annonces/$id'
      fullPath: '/annonces/$id'
      preLoaderRoute: typeof AnnoncesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin': {
      id: '/api/public/admin'
      path: '/api/public/admin'
      fullPath: '/api/public/admin'
      preLoaderRoute: typeof ApiPublicAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moderation/reject': {
      id: '/api/public/moderation/reject'
      path: '/api/public/moderation/reject'
      fullPath: '/api/public/moderation/reject'
      preLoaderRoute: typeof ApiPublicModerationRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/moderation/approve': {
      id: '/api/public/moderation/approve'
      path: '/api/public/moderation/approve'
      fullPath: '/api/public/moderation/approve'
      preLoaderRoute: typeof ApiPublicModerationApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoumettreRoute: SoumettreRoute,
  AnnoncesIdRoute: AnnoncesIdRoute,
  AnnoncesIndexRoute: AnnoncesIndexRoute,
  ApiPublicAdminRoute: ApiPublicAdminRoute,
  ApiPublicModerationApproveRoute: ApiPublicModerationApproveRoute,
  ApiPublicModerationRejectRoute: ApiPublicModerationRejectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
